# -*- coding: utf-8 -*-
"""Sentence similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1syo2pXKcA7lJEX8iaUmtoOnHStCbg2OR
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util
#load the model
model = SentenceTransformer('all-MiniLM-L6-v2')
#take input from user
text1=input('enter text 1: ')
text2=input('enter text 2: ')
#covert text to embeddings
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)
#calculate similarity
similarity = util.cos_sim(embedding1,embedding2)
#show result
print('\nSimilarity Score:',round(float(similarity),2))

if similarity > 0.75:
  print("Similarity level :high")
elif similarity > 0.4:
  print("Similarity level :medium")
else:
  print("Similarity level is :low")

